# Generated by Django 3.2.16 on 2023-02-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0081_unq'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extra',
            field=models.OneToOneField(help_text='Los datos extras del documento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.unq', verbose_name='Extra'),
        ),
    ]
