# Generated by Django 3.2.16 on 2023-02-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0082_document_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNQDOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_uno', models.CharField(db_index=True, default='', help_text='nombres del estudiante.', max_length=255, verbose_name='Nombres')),
                ('texto_dos', models.CharField(db_index=True, default='', help_text='apellido del estudiante.', max_length=255, verbose_name='Apellido')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='extra2',
            field=models.OneToOneField(help_text='Los datos extras del documento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.unqdos', verbose_name='Extra dos'),
        ),
    ]
