# Generated by Django 3.2.16 on 2023-02-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0084_auto_20230206_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia_Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propuesta', models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo Propuesta')),
                ('descripcion_propuesta', models.CharField(db_index=True, help_text='descripcion de la propuesta.', max_length=255, verbose_name='descripcion propuesta')),
                ('nombres', models.CharField(db_index=True, help_text='nombres del estudiante.', max_length=255, verbose_name='nombres')),
                ('apellido', models.CharField(db_index=True, help_text='apellido del estudiante.', max_length=255, verbose_name='apellido')),
                ('tipo_documento', models.CharField(db_index=True, help_text='tipo de documento', max_length=255, verbose_name='tipo documento')),
                ('nro_documento', models.CharField(db_index=True, help_text='numero de documento.', max_length=255, verbose_name='numero documento')),
                ('agente_presentacion', models.CharField(db_index=True, help_text='agente de presentacion.', max_length=255, verbose_name='agente presentacion')),
                ('descripcion_actividad', models.CharField(db_index=True, help_text='descripcion de la actividad.', max_length=255, verbose_name='descripcion actividad')),
                ('fecha', models.DateField(db_index=True, help_text='fecha.', verbose_name='fecha')),
                ('proyecto', models.CharField(db_index=True, help_text='proyecto.', max_length=255, verbose_name='proyecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='extra',
        ),
        migrations.DeleteModel(
            name='UNQ',
        ),
        migrations.AddField(
            model_name='document',
            name='constancia_examen',
            field=models.OneToOneField(blank=True, help_text='si el doc es una constancia de examen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.constancia_examen', verbose_name='constancia examen'),
        ),
    ]
