# Generated by Django 3.2.16 on 2023-02-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0085_auto_20230207_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Aviso_Ultimo_Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propuesta', models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo Propuesta')),
                ('descripcion_propuesta', models.CharField(db_index=True, help_text='descripcion de la propuesta.', max_length=255, verbose_name='descripcion propuesta')),
                ('nombres', models.CharField(db_index=True, help_text='nombres del estudiante.', max_length=255, verbose_name='nombres')),
                ('apellido', models.CharField(db_index=True, help_text='apellido del estudiante.', max_length=255, verbose_name='apellido')),
                ('tipo_documento', models.CharField(db_index=True, help_text='tipo de documento', max_length=255, verbose_name='tipo documento')),
                ('nro_documento', models.CharField(db_index=True, help_text='numero de documento.', max_length=255, verbose_name='numero documento')),
                ('actividad', models.CharField(db_index=True, help_text='aactividad.', max_length=255, verbose_name='actividad')),
                ('fecha_ultimo_examen', models.DateField(db_index=True, help_text='fecha ultimo examen.', verbose_name='fecha ultimo examen')),
                ('email_alternativo', models.EmailField(db_index=True, help_text='email_alternativo.', max_length=255, verbose_name='email_alternativo')),
                ('tel_contacto', models.IntegerField(db_index=True, help_text='email_alternativo.', max_length=255, verbose_name='email_alternativo')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='extra2',
        ),
        migrations.DeleteModel(
            name='UNQDOS',
        ),
        migrations.AddField(
            model_name='document',
            name='solicitud_aviso_ultimo_examen',
            field=models.OneToOneField(blank=True, help_text='si el doc es una solicitud de aviso de ultimo examen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.solicitud_aviso_ultimo_examen', verbose_name='solicitud aviso ultimo examen'),
        ),
    ]
