# Generated by Django 3.2.16 on 2023-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0086_auto_20230207_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tel_contacto',
            field=models.IntegerField(db_index=True, help_text='email_alternativo.', verbose_name='email_alternativo'),
        ),
    ]
