# Generated by Django 3.2.16 on 2023-02-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0088_auto_20230207_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='constancia_examen',
            field=models.ForeignKey(blank=True, help_text='si el doc es una constancia de examen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.constancia_examen', verbose_name='constancia examen'),
        ),
    ]
