# Generated by Django 3.2.16 on 2023-02-14 17:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0089_alter_document_constancia_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia_examen',
            name='domicilio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_index=True, default=['colon 389'], help_text='lista de domicilios.', max_length=255, size=None, verbose_name='lista de domicilios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constancia_examen',
            name='tutores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, default=[{'nombre': 'tuto'}], help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores'),
            preserve_default=False,
        ),
    ]
