# Generated by Django 3.2.16 on 2023-02-14 17:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0090_auto_20230214_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia_aprobacion_materia',
            name='domicilio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_index=True, default=['colon 333'], help_text='lista de domicilios.', max_length=255, size=None, verbose_name='lista de domicilios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constancia_aprobacion_materia',
            name='tutores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, default=[{'nombre': 'pepe'}], help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_aviso_ultimo_examen',
            name='orientaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_index=True, default=['orientacion'], help_text='lista de orientaciones.', max_length=255, size=None, verbose_name='lista de orientaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tutores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, default=[{'nombre': 'argento'}], help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores'),
            preserve_default=False,
        ),
    ]
