# Generated by Django 3.2.16 on 2023-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0091_auto_20230214_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tutores',
        ),
    ]
