# Generated by Django 3.2.16 on 2023-02-14 19:49

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0092_remove_solicitud_aviso_ultimo_examen_tutores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancia_examen',
            name='tutores',
        ),
        migrations.AddField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tutores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, default=[{'nombre': 'juan'}], help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores'),
            preserve_default=False,
        ),
    ]
