# Generated by Django 3.2.16 on 2023-02-15 14:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0093_auto_20230214_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Baja_Propuesta_Guarani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_personal', models.CharField(db_index=True, help_text='plan personal.', max_length=255, verbose_name='plan personal')),
                ('plan', models.CharField(db_index=True, help_text='plan.', max_length=255, verbose_name='plan')),
                ('codigo_propuesta', models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo propuesta')),
                ('descripcion_propuesta', models.CharField(db_index=True, help_text='descripcion de la propuesta.', max_length=255, verbose_name='descripcion propuesta')),
                ('motivos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, help_text='motivos.', size=None, verbose_name='lista de motivos')),
                ('otros_motivos', models.CharField(db_index=True, help_text='otros motivos.', max_length=255, verbose_name='otros motivos')),
                ('nombres', models.CharField(db_index=True, help_text='nombres del estudiante.', max_length=255, verbose_name='nombres')),
                ('apellido', models.CharField(db_index=True, help_text='apellido del estudiante.', max_length=255, verbose_name='apellido')),
                ('tipo_documento', models.CharField(db_index=True, help_text='tipo de documento', max_length=255, verbose_name='tipo documento')),
                ('nro_documento', models.CharField(db_index=True, help_text='numero de documento.', max_length=255, verbose_name='numero documento')),
                ('tutores', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores')),
                ('email_alternativo', models.EmailField(db_index=True, help_text='email_alternativo.', max_length=255, verbose_name='email_alternativo')),
                ('tel_contacto', models.IntegerField(db_index=True, help_text='email_alternativo.', verbose_name='email_alternativo')),
                ('fecha_inscripcion', models.DateField(db_index=True, help_text='fecha inscripcion.', verbose_name='fecha inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='constancia_examen',
            name='tutores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), db_index=True, default=[{'nombre': 'pepe'}], help_text='lista de tutores.', max_length=255, size=None, verbose_name='lista de tutores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constancia_aprobacion_materia',
            name='codigo_propuesta',
            field=models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo propuesta'),
        ),
        migrations.AlterField(
            model_name='constancia_examen',
            name='codigo_propuesta',
            field=models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo propuesta'),
        ),
        migrations.AlterField(
            model_name='document',
            name='constancia_examen',
            field=models.OneToOneField(blank=True, help_text='si el doc es una constancia de examen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.constancia_examen', verbose_name='constancia examen'),
        ),
        migrations.AlterField(
            model_name='solicitud_aviso_ultimo_examen',
            name='codigo_propuesta',
            field=models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo propuesta'),
        ),
        migrations.AddField(
            model_name='document',
            name='solicitud_baja_propuesta_guarani',
            field=models.OneToOneField(blank=True, help_text='si el doc es una solicitud de baja de propuesta guarani.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.solicitud_baja_propuesta_guarani', verbose_name='solicitud baja propuesta guarani'),
        ),
    ]
