# Generated by Django 3.2.16 on 2023-02-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0094_auto_20230215_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Certificado_Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propuesta', models.CharField(db_index=True, help_text='codigo de la propuesta.', max_length=255, verbose_name='codigo propuesta')),
                ('descripcion_propuesta', models.CharField(db_index=True, help_text='descripcion de la propuesta.', max_length=255, verbose_name='descripcion propuesta')),
                ('nombres', models.CharField(db_index=True, help_text='nombres del estudiante.', max_length=255, verbose_name='nombres')),
                ('apellido', models.CharField(db_index=True, help_text='apellido del estudiante.', max_length=255, verbose_name='apellido')),
                ('tipo_documento', models.CharField(db_index=True, help_text='tipo de documento', max_length=255, verbose_name='tipo documento')),
                ('nro_documento', models.CharField(db_index=True, help_text='numero de documento.', max_length=255, verbose_name='numero documento')),
                ('comision', models.CharField(db_index=True, help_text='comision.', max_length=255, verbose_name='comision')),
            ],
            options={
                'verbose_name': 'Solicitud Certificado Aprobacion',
                'verbose_name_plural': 'Solicitud  Certificado Aprobacion',
            },
        ),
        migrations.AlterModelOptions(
            name='constancia_aprobacion_materia',
            options={'verbose_name': 'Constancia Aprobacion Materia', 'verbose_name_plural': 'Constancia Aprobacion Materia'},
        ),
        migrations.AlterModelOptions(
            name='constancia_examen',
            options={'verbose_name': 'Constancia Examen', 'verbose_name_plural': 'Constancia Examen'},
        ),
        migrations.AlterModelOptions(
            name='solicitud_aviso_ultimo_examen',
            options={'verbose_name': 'Solicitud Aviso Ultimo Examen', 'verbose_name_plural': 'Solicitud Aviso Ultimo Examen'},
        ),
        migrations.AlterModelOptions(
            name='solicitud_baja_propuesta_guarani',
            options={'verbose_name': 'Solicitud Baja Propuesta Guarani', 'verbose_name_plural': 'Solicitud Baja Propuesta Guarani'},
        ),
        migrations.AddField(
            model_name='document',
            name='solicitud_certificado_aprobacion',
            field=models.OneToOneField(blank=True, help_text='si el doc es una solicitud de certificado aprobacion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='documents.solicitud_certificado_aprobacion', verbose_name='solicitud certificado aprobacion'),
        ),
    ]
