# Generated by Django 3.2.16 on 2023-02-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0096_auto_20230217_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_equivalencias_guarani',
            name='tutores',
        ),
    ]
