# Generated by Django 3.2.16 on 2023-02-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0098_auto_20230224_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancia_aprobacion_materia',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='constancia_aprobacion_materia',
            name='tutores',
        ),
        migrations.RemoveField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tutores',
        ),
        migrations.RemoveField(
            model_name='solicitud_baja_propuesta_guarani',
            name='tutores',
        ),
    ]
