# Generated by Django 3.2.16 on 2023-02-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0099_auto_20230227_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_aviso_ultimo_examen',
            name='tel_contacto',
            field=models.IntegerField(db_index=True, help_text='telefono contacto.', verbose_name='telefono contacto'),
        ),
        migrations.AlterField(
            model_name='solicitud_baja_propuesta_guarani',
            name='tel_contacto',
            field=models.IntegerField(db_index=True, help_text='telefono contacto.', verbose_name='telefono contacto'),
        ),
    ]
